= Deploying microservices with Pivotal CF using a CI pipeline in Jenkins

== Creating the Jenkins pipeline

* Login to a Jenkins server. 
* Explore the existing projects, their build status and logs.
* Now let's create a new CI pipeline for you. On the left menu, click "New Item".
* Choose "Freestyle Project". Give it the name "microservices-bootcamp-<yourname>". Please use this convention so we can recycle these after the bootcamp.
* On "Github project", enter "https://github.com/bbertka/PCF-demo"
* On source code management, click "GIT" and enter the following repository info:
- Repository URL: https://github.com/bbertka/PCF-demo
- Branch: */micro-services
* On "Build Triggers", select "Build when a change is pushed to GitHub"
* If you have an artifactory server available:  On "Build Environment", select "Maven3-Artifactory Integration". Select your Artifactory Server. Click "Refresh Repositories" and select the following repositories: "ext-release-local" for releases and "ext-snapshot-local" for snapshots. Also select "Capture and publish build info". When demo'ing,  *don't* select "Deploy artifacts to Artifactory", as it would require additional storage space per deploy.
* On "Build", setup as following:
- Invoke Gradle:  Use gradle wrapper, check make executable, check From Root Build Script Dir, tasks: assemble, Root Build Script: PCFDemo-producer/
- Invoke Gradle:  Use gradle wrapper, check make executable, check From Root Build Script Dir, tasks: assemble, Root Build Script: PCFDemo-map/
- Force GRADLE_USER_HOME to use workspace
- Execute Shell:
* Set Build Triggers with desired polling for repo changes: "*/1 * * * *" is each minute
----
DEPLOYED_VERSION_CMD=$(CF_COLOR=false cf apps | grep 'mapUS.' | cut -d" " -f1)
export BUILD_VERSION="1.2"
export DEPLOYED_VERSION_CMD
echo DEPLOYED_VERSION_CMD
export ROUTE_VERSION="default"
echo "Deployed Version: $DEPLOYED_VERSION"
echo "Route Version: $ROUTE_VERSION"
export API=http://<your_cf_api>

wget -O cf.tgz https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.13.0&source=github-rel
sleep 5
tar -zxvf ./cf.tgz

./cf api --skip-ssl-validation $API
./cf login -u <user> -p <password> -o <org> -s <space>

./cf push "Service Activation Map" -f PCFDemo-map/manifest.yml --no-start
./cf bind-service "Service Activation Map" myrabbit
./cf bind-service "Service Activation Map" myeureka
./cf restart "Service Activation Map"

./cf push "Fantasy Sports Pilot" -f PCFDemo-producer/manifest-pilot.yml --no-start
./cf bind-service "Fantasy Sports Pilot" myrabbit
./cf bind-service "Fantasy Sports Pilot" myeureka
./cf restart "Fantasy Sports Pilot"

./cf push "East Customer Regions" -f PCFDemo-producer/manifest-east.yml --no-start
./cf bind-service "East Customer Regions" myrabbit
./cf bind-service "East Customer Regions" myeureka
./cf restart "East Customer Regions"
./cf scale "East Customer Regions" -i 5

./cf push "South Customer Regions" -f PCFDemo-producer/manifest-south.yml --no-start
./cf bind-service "South Customer Regions" myrabbit
./cf bind-service "South Customer Regions" myeureka
./cf restart "South Customer Regions"
./cf scale "South Customer Regions" -i 4

----

* If you'd like to add any additional steps (like smoke tests) to the build, add as a "Post Build Action".
* Save changes.
* Detail your new project. On the menu, click "Build now". 
* As a new build starts, detail it and click on "Console Output" to see the build / deploy real-time logging info.
* Do any troubleshoot needed until you have a clean build.
* Congratulations! You have created your CI pipeline. 

== Demo

* Clean-up your environment on Pivotal CF, to have an empty space to demo.
* Login to Jenkins
* Click on your project to detail
* Click "build now". 
* Check "Console output" as jenkins downloads the source code and deploys it to Pivotal CF.
* Navigate back to Pivotal CF Web Console and show service created and app deployed. 
* Demo the app
